-- Possível Pro — biblioteca multimídia e nuvem pessoal.
-- Permite que assinantes Pro armazenem e acessem apenas conteúdo próprio,
-- licenciado ou em domínio público. O bucket é privado e cada usuário só
-- enxerga a própria pasta.

create table if not exists public.pro_media_library (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null check (kind in ('movie', 'series', 'book', 'music')),
  title text not null check (char_length(title) between 1 and 180),
  storage_path text not null unique,
  mime_type text,
  size_bytes bigint not null default 0 check (size_bytes >= 0),
  created_at timestamptz not null default now()
);

create or replace function public.enforce_pro_media_quota()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  used_bytes bigint;
begin
  select coalesce(sum(size_bytes), 0)
    into used_bytes
  from public.pro_media_library
  where owner_id = new.owner_id;

  if used_bytes + new.size_bytes > 2147483648 then
    raise exception 'Limite da nuvem Pro de 2 GB atingido';
  end if;

  return new;
end;
$$;

revoke all on function public.enforce_pro_media_quota() from public, anon, authenticated;

drop trigger if exists pro_media_library_quota on public.pro_media_library;
create trigger pro_media_library_quota
before insert on public.pro_media_library
for each row execute function public.enforce_pro_media_quota();

alter table public.pro_media_library enable row level security;

drop policy if exists pro_media_library_select_own on public.pro_media_library;
create policy pro_media_library_select_own
on public.pro_media_library
for select
to authenticated
using (
  owner_id = auth.uid()
  and public.get_effective_plan(auth.uid()) = 'pro'
);

drop policy if exists pro_media_library_insert_own on public.pro_media_library;
create policy pro_media_library_insert_own
on public.pro_media_library
for insert
to authenticated
with check (
  owner_id = auth.uid()
  and public.get_effective_plan(auth.uid()) = 'pro'
);

drop policy if exists pro_media_library_delete_own on public.pro_media_library;
create policy pro_media_library_delete_own
on public.pro_media_library
for delete
to authenticated
using (
  owner_id = auth.uid()
  and public.get_effective_plan(auth.uid()) = 'pro'
);

grant select, insert, delete on public.pro_media_library to authenticated;
grant usage, select on sequence public.pro_media_library_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'pro-library',
  'pro-library',
  false,
  524288000,
  array[
    'video/mp4',
    'video/webm',
    'audio/mpeg',
    'audio/mp4',
    'audio/ogg',
    'application/pdf',
    'application/epub+zip',
    'text/plain'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Cada objeto deve ficar em: <user-id>/<kind>/<arquivo>.
drop policy if exists pro_library_objects_select_own on storage.objects;
create policy pro_library_objects_select_own
on storage.objects
for select
to authenticated
using (
  bucket_id = 'pro-library'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.get_effective_plan(auth.uid()) = 'pro'
);

drop policy if exists pro_library_objects_insert_own on storage.objects;
create policy pro_library_objects_insert_own
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'pro-library'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.get_effective_plan(auth.uid()) = 'pro'
);

drop policy if exists pro_library_objects_delete_own on storage.objects;
create policy pro_library_objects_delete_own
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'pro-library'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.get_effective_plan(auth.uid()) = 'pro'
);

notify pgrst, 'reload schema';
